### ISSUE TITLE
Pipeline settings using yaml

### ISSUE THREAD

**Issue by BerndDoser** [HITS-TOS/TACO#5]
Parameters for all modules will be gathered for the TACO pipeline in a single yaml file, which will be a argument of the pipeline script. Here shown as example:

```
pipeline:
    - filter:
        width: 40
        remove_gaps: -1
        output_filtered: filtered.cvs
    - pds:
        output_pds: pds.cvs
    - oversampled_pds:
        oversample_factor:
            small_dataset: 5
            large_dataset: 2
        output_pds: oversampled_pds.cvs
    - numax_estimate:
        filter_width: 0.2
    - background_fit:
        bins: 300
    - peakFind:
        snr: 1.1
        prob: 0.0001
        minAIC: 2
    - peaksMLE:
        minAIC: 2
    - peakBagModeId02:
    - peakFind:
        snr: 1.1
        prob: 0.0001
        minAIC: 2
        removel02: true
    - peaksMLE:
        minAIC: 2
        removel02: true
        init: peaksMLE.csv
        mixedpeaks: mixedpeaks.csv
    - peaksMLE:
        minAIC: 2
        finalfit: true
```
Because of multiple calls of modules, we have to use a ordered structure for the modules. Therefore, to access a single parameter the position and the module name is needed, e.g. `['pipeline'][0]['filter']['width']`.

Alternatively, it would be possible to choose unique module names, e.g. `peaksMLE_final`, which would allow an unordered structure.

In principle, it is also possible to define the order of module calls by defining the data interface of the modules.
